import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowUp,
  faBars,
  faBolt,
  faBullseye,
  faCalendarDays,
  faChartLine,
  faChevronDown,
  faCheck,
  faCircle,
  faClock,
  faDumbbell,
  faEnvelope,
  faFileLines,
  faFlag,
  faFutbol,
  faHandshake,
  faHouse,
  faImages,
  faLocationDot,
  faMedal,
  faMessage,
  faPhone,
  faPersonRunning,
  faShirt,
  faStar,
  faTrophy,
  faUser,
  faUsers,
  faGaugeHigh,
  faRightToBracket,
  faEye,
  faFloppyDisk,
  faRotateRight,
  faTrash,
  faPlus,
  faImage,
  faPaperPlane,
  faLink,
  faAward,
  faTimeline,
  faAddressCard,
  faTriangleExclamation,
  faRotateLeft,
  faGlobe,
  faMoon,
  faSun
} from "@fortawesome/free-solid-svg-icons";

const iconMap = {
  "arrow-up": faArrowUp,
  bars: faBars,
  football: faFutbol,
  futbol: faFutbol,
  ball: faFutbol,
  shirt: faShirt,
  tshirt: faShirt,
  running: faPersonRunning,
  runner: faPersonRunning,
  flag: faFlag,
  calendar: faCalendarDays,
  target: faBullseye,
  bullseye: faBullseye,
  handshake: faHandshake,
  clock: faClock,
  trophy: faTrophy,
  medal: faMedal,
  star: faStar,
  location: faLocationDot,
  "location-dot": faLocationDot,
  "chevron-down": faChevronDown,
  check: faCheck,
  chevron: faChevronDown,
  chart: faChartLine,
  "chart-line": faChartLine,
  bolt: faBolt,
  dumbbell: faDumbbell,
  images: faImages,
  image: faImage,
  file: faFileLines,
  "file-lines": faFileLines,
  envelope: faEnvelope,
  message: faMessage,
  phone: faPhone,
  user: faUser,
  users: faUsers,
  home: faHouse,
  gauge: faGaugeHigh,
  login: faRightToBracket,
  eye: faEye,
  save: faFloppyDisk,
  refresh: faRotateRight,
  restore: faRotateLeft,
  warning: faTriangleExclamation,
  trash: faTrash,
  plus: faPlus,
  send: faPaperPlane,
  link: faLink,
  award: faAward,
  timeline: faTimeline,
  card: faAddressCard,
  circle: faCircle,
  globe: faGlobe,
  language: faGlobe,
  moon: faMoon,
  sun: faSun,

  "⚽": faFutbol,
  "👕": faShirt,
  "🏃": faPersonRunning,
  "🇪🇬": faFlag,
  "📅": faCalendarDays,
  "🎯": faBullseye,
  "🤝": faHandshake,
  "⏱️": faClock,
  "🏆": faTrophy,
  "🥇": faMedal,
  "⭐": faStar,
  "📍": faLocationDot,
  "📈": faChartLine,
  "⚡": faBolt,
  "🖼️": faImages,
  "📄": faFileLines,
  "📩": faEnvelope,
  "👤": faUser,
  "📌": faCircle
};

export function getIcon(iconName) {
  if (!iconName) return faCircle;
  const cleanName = String(iconName).trim().toLowerCase();
  return iconMap[iconName] || iconMap[cleanName] || faCircle;
}

export default function FaIcon({ name, className = "", title }) {
  return <FontAwesomeIcon icon={getIcon(name)} className={className} title={title} />;
}
